language: cpp
dist: trusty
sudo: required
compiler:
  - gcc
os:
  - linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
script:
  - export CC=gcc-7
  - export CXX=g++-7

install:
  - sudo apt-get update
  - sudo apt-get install libcurl4-openssl-dev
  - sudo apt-get install libboost-all-dev
  - sudo apt-get install  libffi-dev libssl-dev libxml2-dev libxslt1-dev libjpeg8-dev zlib1g-dev

script:
  - cd libbittrex;mkdir build;cd build
  - cmake .. && cmake --build .
  - sudo make install
  
  - cd tests
  - cmake .
  - make
  - ./bittrex_api_test --report_level=detailed
