language: cpp
dist: trusty
sudo: required
compiler:
  - gcc
os:
  - linux
addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
before_install:
  - sudo apt-get install libcurl4-openssl-dev
  - sudo apt-get install libboost-all-dev
  - sudo apt-get install  libffi-dev libssl-dev libxml2-dev libxslt1-dev libjpeg8-dev zlib1g-dev

script:
  - export CC=gcc-7
  - export CXX=g++-7
  # Build steps
  - cd build
  - ./builder.sh

  # Run tests
  - make test
