version: 2
jobs:
  build:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install build-essential
      - run: sudo apt-get install libcurl4-openssl-dev
      - run: sudo apt-get install libboost-all-dev
      - run: sudo apt-get install  libffi-dev libssl-dev libxml2-dev libxslt1-dev libjpeg8-dev zlib1g-dev


      - run: cd libbittrex;mkdir build;cd build
      - run: cmake .. && cmake --build .
      - run: sudo make install


      - run: cd tests
      - run: cmake .
      - run: make
      - run: ./bittrex_api_test --report_level=detailed
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      
